baseURL = "https://ytakaya.github.io/blog/"
languageCode = "ja"
title = "yamazooooe's blog"
theme = "ananke"
publishDir = "docs"
canonifyurls = true

SectionPagesMenu = "main"

[taxonomies]
tag = "tags"
category = "categories"

[params]
  favicon = ""
  site_logo = ""
  description = ""
  facebook = ""
  twitter = "https://twitter.com/yamazooooe"
  instagram = ""
  youtube = ""
  github = "https://github.com/ytakaya"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/header.JPG"
  recent_posts_number = 2